---
name: "service_state_remediation_rule"
pack: "uem_stackstorm"
description: "Rule to remediate service state alert"
enabled: true

trigger:
    type: "core.st2.webhook"
    parameters:
        url: "service-start"

action:
    ref: "uem_stackstorm.remediate_service_state"
    parameters: 
        data: "{{ trigger.body }}"